Исследование надежности заемщиков

Задание 1. Импортируйте библиотеку pandas. Считайте данные из csv-файла в датафрейм и сохраните в переменную data

In [1]:
import pandas as pd

data = pd.read_csv('credit_data.csv')
display(data)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
...,...,...,...,...,...,...,...,...,...,...,...,...
21520,1,-4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем
21522,1,-2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,-3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,-1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

Задание 2. Выведите первые 20 строчек датафрейма data на экран

In [2]:
data.head(20)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля

Задание 3. Выведите основную информацию о датафрейме с помощью метода info()

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   children          21525 non-null  int64
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64
 3   education         21525 non-null  str
 4   education_id      21525 non-null  int64
 5   family_status     21525 non-null  str
 6   family_status_id  21525 non-null  int64
 7   gender            21525 non-null  str
 8   income_type       21525 non-null  str
 9   debt              21525 non-null  int64
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  str
dtypes: float64(2), int64(5), str(5)
memory usage: 1.6 MB

Задание 4. Выведите количество пропущенных значений для каждого столбца

In [4]:
print(data.isna().sum())

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

Задание 5. В двух столбцах есть пропущенные значения. Один из них — days_employed. Пропуски в этом столбце вы обработаете на следующем этапе. Другой столбец с пропущенными значениями — total_income — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца income_type. Например, у человека с типом занятости сотрудник пропуск в столбце total_income должен быть заполнен медианным доходом среди всех записей с тем же типом

In [5]:
data['income_type'].unique()
data['income_type'].value_counts()

income_type
сотрудник          11119
компаньон           5085
пенсионер           3856
госслужащий         1459
безработный            2
предприниматель        2
студент                1
в декрете              1
Name: count, dtype: int64

In [6]:
for d in data['income_type'].unique():
    data.loc[(data['income_type'] == d) & (data['total_income'].isna()), 'total_income'] = \
    data.loc[(data['income_type'] == d), 'total_income'].mean()

print(data['total_income'].isna().sum())

0

Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. таким артефактом будет отрицательное количество дней трудового стажа в столбце days_employed. Для реальных данных это нормально. Обработайте значения в этом столбце: замените все отрицательные значения положительными с помощью метода abs()

In [7]:
data['days_employed'] = data['days_employed'].abs()
data.head()

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу

Задание 7. Для каждого типа занятости выведите среднее и медианное значение трудового стажа days_employed

In [8]:
for d in data['income_type'].unique():
    days_employed_mean = data.loc[(data['income_type'] == d), 'days_employed'].mean().round(2)
    days_employed_median = data.loc[(data['income_type'] == d), 'days_employed'].median().round(2)
    print(d, days_employed_mean, days_employed_median)

сотрудник 2326.5 1574.2
пенсионер 365003.49 365213.31
компаньон 2111.52 1547.38
госслужащий 3399.9 2689.37
безработный 366413.65 366413.65
предприниматель 520.85 520.85
студент 578.75 578.75
в декрете 3296.76 3296.76

Задание 8. Выведите перечень уникальных значений столбца children

In [9]:
data['children'].value_counts()

children
 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: count, dtype: int64

Задание 9. В столбце children есть два аномальных значения. Удалите строки, в которых встречаются такие аномальные значения из датафрейма data

In [10]:
data = data[data['children'] != 20]
data = data[data['children'] != -1]

Задание 10. Ещё раз выведите перечень уникальных значений столбца children, чтобы убедиться, что артефакты удалены

In [11]:
data['children'].value_counts()

children
0    14149
1     4818
2     2055
3      330
4       41
5        9
Name: count, dtype: int64

Задание 11. Заполните пропуски в столбце days_employed медианными значениями по каждого типа занятости income_type

In [12]:
for d in data['income_type'].unique():
    data.loc[(data['income_type'] == d) & (data['days_employed'].isna()), 'days_employed'] = \
    data.loc[(data['income_type'] == d), 'days_employed'].median()
    
print(data['days_employed'].isna().sum())

0

Задание 12. Убедитесь, что все пропуски заполнены. Проверьте себя и ещё раз выведите количество пропущенных значений для каждого столбца

In [13]:
print (data.isna().sum())

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

Задание 13. Замените вещественный тип данных в столбце total_income на целочисленный с помощью метода astype()

In [14]:
data['total_income'] = data['total_income'].astype(int)
print(data['total_income'].dtypes)

int32

Задание 14. Обработайте неявные дубликаты в столбце education. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите их к нижнему регистру

In [15]:
data['education'] = data['education'].str.lower()
data['education'].value_counts()

education
среднее                15136
высшее                  5237
неоконченное высшее      741
начальное                282
ученая степень             6
Name: count, dtype: int64

Задание 15. Выведите на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалите их

In [16]:
print (data.duplicated().sum())

71

In [17]:
data = data.drop_duplicates(keep = 'first')
data = data.reset_index(drop = True)

print (data.duplicated().sum())

0

Задание 16. На основании диапазонов, указанных ниже, создайте в датафрейме `data` столбец `total_income_category` с категориями:

- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.


Например, кредитополучателю с доходом 25000 нужно назначить категорию `'E'`, а клиенту, получающему 235000, — `'B'`. Используйте собственную функцию с именем `categorize_income()` и метод `apply()`

In [18]:
def categorize_income(total_income):
    if total_income <= 30000:
        return 'E'
    if total_income > 30000 and total_income <= 50000:
        return 'D'
    if total_income > 50000 and total_income <= 200000:
        return 'C'
    if total_income > 200000 and total_income <= 1000000:
        return 'B'
    return 'A'

In [19]:
print(categorize_income(35000))

D

In [20]:
print(categorize_income(1500000))

A

In [21]:
data ['total_income_category'] = data['total_income'].apply(categorize_income)

data[['total_income', 'total_income_category']].head(10)

   total_income total_income_category
0        253875                     B
1        112080                     C
2        145885                     C
3        267628                     B
4        158616                     C
5        255763                     B
6        240525                     B
7        135823                     C
8         95856                     C
9        144425                     C

Задание 17. Выведите на экран перечень уникальных целей взятия кредита из столбца purpose

In [22]:
data['purpose'].value_counts()

purpose
свадьба                                   790
на проведение свадьбы                     763
сыграть свадьбу                           760
операции с недвижимостью                  672
покупка коммерческой недвижимости         658
покупка жилья для сдачи                   649
операции с жильем                         647
операции с коммерческой недвижимостью     645
жилье                                     641
покупка жилья                             640
покупка жилья для семьи                   637
недвижимость                              631
строительство собственной недвижимости    628
операции со своей недвижимостью           623
строительство жилой недвижимости          620
строительство недвижимости                619
покупка своего жилья                      619
покупка недвижимости                      616
ремонт жилью                              604
покупка жилой недвижимости                602
на покупку своего автомобиля              504
заняться высшим образованием              496
автомобиль                                491
сделка с подержанным автомобилем          481
автомобили                                476
свой автомобиль                           473
на покупку подержанного автомобиля        471
на покупку автомобиля                     469
приобретение автомобиля                   459
дополнительное образование                455
сделка с автомобилем                      455
высшее образование                        446
получение дополнительного образования     444
образование                               442
получение образования                     440
профильное образование                    432
получение высшего образования             425
заняться образованием                     408
Name: count, dtype: int64

Задание 18. Создайте функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, в который войдут следующие категории:

- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

Например, если в столбце `purpose` находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`

Используйте собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучите данные в столбце `purpose` и определите, какие подстроки помогут вам правильно определить категорию

In [23]:
def categorize_purpose(p):
    if ('авто' in p) == True:
        return 'операции с автомобилем'
    if ('недвиж' in p) == True:
        return 'операции с недвижимостью'
    if ('жиль' in p) == True:
        return 'операции с недвижимостью'
    if ('свадьб' in p) == True:
        return 'проведение свадьбы'
    return 'получение образования'

In [24]:
data ['purpose_category'] = data['purpose'].apply(categorize_purpose)

print (data[['purpose', 'purpose_category']].head(10))

                      purpose          purpose_category
0               покупка жилья  операции с недвижимостью
1     приобретение автомобиля    операции с автомобилем
2               покупка жилья  операции с недвижимостью
3  дополнительное образование     получение образования
4             сыграть свадьбу        проведение свадьбы
5               покупка жилья  операции с недвижимостью
6           операции с жильем  операции с недвижимостью
7                 образование     получение образования
8       на проведение свадьбы        проведение свадьбы
9     покупка жилья для семьи  операции с недвижимостью

In [25]:
display(data)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,total_income_category,purpose_category
0,1,8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,покупка жилья,B,операции с недвижимостью
1,1,4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,приобретение автомобиля,C,операции с автомобилем
2,0,5623.422610,33,среднее,1,женат / замужем,0,M,сотрудник,0,145885,покупка жилья,C,операции с недвижимостью
3,3,4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,дополнительное образование,B,получение образования
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,сыграть свадьбу,C,проведение свадьбы
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21326,1,4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791,операции с жильем,B,операции с недвижимостью
21327,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999,сделка с автомобилем,C,операции с автомобилем
21328,1,2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672,недвижимость,C,операции с недвижимостью
21329,3,3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093,на покупку своего автомобиля,B,операции с автомобилем
21330,2,1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047,на покупку автомобиля,C,операции с автомобилем

Задание 19. Как разные цели кредита влияют на его возврат в срок?

1) Постройте таблицу типа: 
    
- категория,
    
- общее количество клиентов в разрезе категорий
    
- общее количество должников (также, по категориям)
    
- доля должников от общего количества клиентов.

Ты можешь использовать такую конструкцию (с использованием методов groupby() и agg()):
    
    df.groupby('...')['debt'].agg(['count', 'sum', 'mean'])


Изменить наименование столбцов в таблице так, чтобы они отражали содержание, можно с помощью rename():

    df = df.rename(columns={'old_name_1': 'new_name1', ...})

2) Обратите внимание, что выборки несбалансированны, в некоторых категориях количество клиентов очень мало, поэтому выявить корректную зависимость можно, сравнив самые большие категории.

In [26]:
data_grouped = data.groupby('purpose_category')['debt'].agg(['count', 'sum', 'mean'])
data_grouped = data_grouped.rename(columns={'count': 'clients', 'sum': 'debtors', 'mean': 'debtors_rate'})

display(data_grouped)

                          clients  debtors  debtors_rate
purpose_category
операции с автомобилем       4279      400      0.093480
операции с недвижимостью    10751      780      0.072551
получение образования        3988      369      0.092528
проведение свадьбы           2313      183      0.079118